_project_/urls.py
# coding=utf-8
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.views.generic import TemplateView
from auth.urls import urlpatterns as auth_urlpatterns

import registration.views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'^registration/', registration.views.register, name='registration'),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += auth_urlpatterns

auth/urls.py
# coding=utf-8
__author__ = 'Таника'
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
)

polls/urls.py
# coding=utf-8
__author__ = 'Таника'

from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='poll_index'),
    url(r'^add/$', views.add_poll, name='add_poll'),
    url(r'^(?P<poll_id>\d+)/add_choice/$', views.add_choice, name='add_choice'),
    url(r'^(?P<poll_id>\d+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<poll_id>\d+)/poll_del/$', views.poll_delete, name='poll_del'),
    url(r'^(?P<poll_id>\d+)/choice_del/(?P<choice_id>\d+)/$', views.choice_delete, name='choice_del'),
    url(r'^del_message/$', views.del_message, name='del_message'),
    url(r'^(?P<poll_id>\d+)/send/$', views.send, name='send'),
    url(r'^(?P<recv_id>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<recv_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<poll_id>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/results/votes_details/$', views.votes_details, name='votes_details'),
)

_project_/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
    <link href="{% static 'bootstrap-3.1.1-dist/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'bootstrap-3.1.1-dist/js/bootstrap.min.js' %}"></script>
</head>
<body>
{% block exit %}
{% endblock %}
<h1>Обмен опросниками</h1>

<p>
    {% block title %}
    {% endblock %}
</p>

{% block content %}

{% endblock %}

{% block footer %}
    <footer style="margin-top: 20px;">
        <a href="{% url "polls:poll_index" %}">
            <button type="button" class="btn btn-primary button" data-title="Вернуться в профиль">
                <span class="glyphicon glyphicon-home"></span>
            </button>
        </a>
    </footer>
{% endblock %}
</body>
</html>

_project_/templates/base_user.html
{% extends "base.html" %}
{% block exit %}
    <p style="text-align: right;"><a href="{% url "logout" %}">Выйти</a></p>
{% endblock %}
{% block title %}
{#    <p style="text-align: right;"><a href="{% url "logout" %}">Выйти</a></p>#}
    <h2>Пользователь:
    {{ user.get_username}}
    </h2>
{% endblock %}

_project_/templates/index.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
    Добро пожаловать в сервис отправки опросов!
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <script>window.location = '{% url 'polls:poll_index' %}';</script>
    {% else %}
        <p><a href="{% url "login" %}">Войти</a> или <a href="{% url "registration" %}">Зарегистрироваться</a></p>
    {% endif %}

{% endblock %}
{% block footer %}
{% endblock %}