_project_/urls.py
# coding=utf-8
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.views.generic import TemplateView
from auth.urls import urlpatterns as auth_urlpatterns

import registration.views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'^registration/', registration.views.register, name='registration'),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += auth_urlpatterns

auth/urls.py
# coding=utf-8
__author__ = 'Таника'
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
)

polls/urls.py
# coding=utf-8
__author__ = 'Таника'

from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='poll_index'),
    url(r'^add/$', views.add_poll, name='add_poll'),
    url(r'^(?P<poll_id>\d+)/add_choice/$', views.add_choice, name='add_choice'),
    url(r'^(?P<poll_id>\d+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<poll_id>\d+)/poll_del/$', views.poll_delete, name='poll_del'),
    url(r'^(?P<poll_id>\d+)/choice_del/(?P<choice_id>\d+)/$', views.choice_delete, name='choice_del'),
    url(r'^del_message/$', views.del_message, name='del_message'),
    url(r'^(?P<poll_id>\d+)/send/$', views.send, name='send'),
    url(r'^(?P<recv_id>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<recv_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<poll_id>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/results/votes_details/$', views.votes_details, name='votes_details'),
)

polls/models.py
# coding=utf-8
# Create your models here.
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User


class Poll(models.Model):
    user = models.ForeignKey(User)
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', auto_now=True)

    def __unicode__(self):
        return self.question

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date < now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text


class ReceivePolls(models.Model):
    user = models.ForeignKey(User)
    poll = models.ForeignKey(Poll)
    is_answered = models.BooleanField(default=False)
    answer = models.CharField(max_length=200, blank=True)

    def __unicode__(self):
        return self.poll.question

polls/forms.py
# coding=utf-8
__author__ = 'Таника'

# coding=utf-8
from django import forms
from polls.models import Poll, Choice, ReceivePolls


class AddPollForm(forms.ModelForm):
    question = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Вопрос', 'autofocus':'autofocus'}), label='')
    class Meta:
        model = Poll
        fields = ('question',)


class AddChoiceForm(forms.ModelForm):
    choice_text = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Варианты ответов', 'autofocus':'autofocus'}), label='')
    class Meta:
        model = Choice
        fields = ('choice_text',)


class SendPollForm(forms.ModelForm):
    class Meta:
        model = ReceivePolls
        fields = ('user', )

polls/views.py
# coding=utf-8
# Create your views here.

from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from polls.forms import AddPollForm, AddChoiceForm, SendPollForm

from polls.models import Choice, Poll, ReceivePolls


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'poll_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Poll.objects.filter(user=self.request.user.pk)

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['recv_polls'] = ReceivePolls.objects.filter(user=self.request.user.pk)
        # print(list(ReceivePolls.objects.filter(user=self.request.user.pk)))
        return context


class DetailView(generic.DetailView):
    model = ReceivePolls
    template_name = 'polls/detail.html'
    pk_url_kwarg = 'recv_id'

    # def get_queryset(self):
    #     return ReceivePolls.objects.all()


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'
    pk_url_kwarg = 'poll_id'


def add_poll(request):
    # return render(request, 'polls/add_poll.html')
    if request.method == "POST":
        form = AddPollForm(request.POST)
        if form.is_valid():
            poll = form.save(commit=False)
            poll.user = request.user
            poll.save()
            return redirect('polls:add_choice', poll_id=poll.id)

    else:
        form = AddPollForm()  #request.user.username)

    poll = Poll.objects.all()

    return render(request, 'polls/add_poll.html',
                  {
                      'poll': poll,
                      'form': form,
                  })


def add_choice(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)

    if request.method == "POST":
        form = AddChoiceForm(request.POST)
        if form.is_valid():
            choice = form.save(commit=False)
            choice.poll = poll
            choice.save()
            return redirect('polls:add_choice', poll_id=poll_id)

    else:
        form = AddChoiceForm()  #request.user.username)

    choices = poll.choice_set.all()

    return render(request, 'polls/add_choice.html', {
        'choices': choices,
        'form': form,
        'poll': poll,
    })


def vote(request, recv_id):
    recv_poll = get_object_or_404(ReceivePolls, pk=recv_id)
    try:
        selected_choice = recv_poll.poll.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',
                      {'poll': recv_poll, 'error_message': "You didn't select a choice.", })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        recv_poll.is_answered = True
        recv_poll.answer = selected_choice.choice_text
        recv_poll.save()
        return redirect('polls:results', poll_id=recv_poll.poll.id)


def send(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)

    if request.method == "POST":
        form = SendPollForm(request.POST)
        if form.is_valid():
            recv_polls = form.save(commit=False)
            recv_polls.poll = poll
            recv_polls.save()
            return redirect('polls:poll_index')

    else:
        form = SendPollForm()  #request.user.username)

    return render(request, 'polls/send.html', {
        'poll': poll,
        'form': form,
    })


def votes_details(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    selected_poll = ReceivePolls.objects.filter(poll_id=poll.id)
    print selected_poll
    choices = Choice.objects.filter(poll_id=poll.id)
    print choices
    for choice in choices:
        print choice.choice_text
    return render(request, 'polls/votes_details.html', {
        'poll': poll,
        'selected_poll': selected_poll,
        'choices': choices
    })


def poll_delete(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    if request.user == poll.user:
        poll.delete()
    return redirect('polls:poll_index')


def edit(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    choices = Choice.objects.filter(poll_id=poll.id)
    if request.method == "POST":
        k = request.POST.keys()
        for key in k:
            if key.startswith("choice_"):
                text, index = key.split('_', 1)
                choice = Choice.objects.get(id=index)
                if request.POST[key] == '':
                    choice.delete()
                else:
                    choice.choice_text = request.POST[key]
                    # print choice.choice_text
                    choice.save()
            else:
                if key.startswith("poll_question"):
                    if request.POST[key] == '':
                        poll.delete()
                        print "ddd"
                        return redirect('polls:del_message')
                    else:
                        poll.question = request.POST[key]
                        poll.save()
    return render(request, 'polls/edit.html', {
        'poll': poll,
        'choices': choices
    })


def choice_delete(request, poll_id, choice_id):
    poll = get_object_or_404(Poll, id=poll_id)
    choice = get_object_or_404(Choice, id=choice_id)
    if request.user == poll.user:
        choice.delete()
    return redirect('polls:edit', poll_id=poll.id)


def del_message(request):
    return render(request, 'polls/del_message.html')

_project_/templates/polls/add_choice.html
{% extends "base_user.html" %}
{% block content %}
    <form action="." method="post">{% csrf_token %}
        <div class="content_box" style="width: 40%;">
            <h3 style="color: #ee4c8d;">Вопрос: {{ poll }}</h3>
            {% for x in choices %}
                <p>{{ x.choice_text }}</p>
            {% empty %}
                <p>Нет вариантов!</p>
            {% endfor %}
        </div>
        {{ form.as_p}}
        <br/>
        <input type="submit" value="Добавить" class="btn btn-primary button bt" style="margin-top: -20px"/>
    </form>
{% endblock %}

_project_/templates/polls/add_poll.html
{% extends "base_user.html" %}
{% block content %}
    <form action="{% url 'polls:add_poll' %}" method="post">{% csrf_token %}
        {{ form.as_p}}
        <br/>
        <input type="submit" value="Добавить варианты ответов" class="btn btn-primary button bt"/>
    </form>
{% endblock %}

_project_/templates/polls/del_message.html
{% extends "base_user.html" %}
{% block content %}
    Вы удалили редактируемый опрос!
{% endblock %}

_project_/templates/polls/detail.html
{% extends "base_user.html" %}
    {% block content %}
        {% if receivepolls.is_answered %}
            <script>window.location = '{% url 'polls:results' poll_id=receivepolls.poll.id %}'</script>
        {% endif %}
        <div class="content_box">
            <h3 style="color: #ee4c8d;">{{ receivepolls.poll.question }}</h3>

            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            <form action="{% url 'polls:vote' receivepolls.id %}" method="post">
                {% csrf_token %}
                <div class="choices">
                    {% for choice in receivepolls.poll.choice_set.all %}
                        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
                        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
                    {% endfor %}
                </div>
                {% if receivepolls.poll.choice_set.all.count != 0 %}
                    <input type="submit" value="Голосовать" class="btn btn-primary button bt"/>
                {% endif %}
            </form>
        </div>

    {% endblock %}

_project_/templates/polls/edit.html
{% extends "base_user.html" %}
{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        <p>Вопрос: <input type="text" name="poll_question" value="{{ poll.question }}"/></p>

        <p>Варианты ответов</p>
        {% for choice in choices %}
            <p>
                <input type="text" name="choice_{{ choice.id }}" value="{{ choice.choice_text }}"/>
                <a href="{% url 'polls:choice_del' poll_id=poll.id choice_id=choice.id %}">
                        <button type="button" class="btn btn-primary button" data-title="Удалить ответ">
                            <span class="glyphicon glyphicon-remove"></span>
                        </button>
                    </a>
            </p>
        {% endfor %}
        <input type="submit" value="Сохранить" class="btn btn-primary button" style="margin: 10px"/>
        <div style="margin-top:10px; display: inline-block">
            <a href="{% url "polls:add_choice" poll_id=poll.id %}">
                    <button type="button" class="btn btn-primary button" data-title="Добавить вариант ответа">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>
            </a>
        </div>
    </form>
{#    <br/>#}

{% endblock %}

_project_/templates/polls/index.html
{% extends "base_user.html" %}
{% block content %}
    <div class="my_container">
        <div class="user_list_poll">
            <h3 class="my_h3">Мои опросы</h3>
            {% if poll_list %}
                {% for poll in poll_list %}
                    <p class="my_polls">
                        <a href="{% url 'polls:poll_del' poll_id=poll.id %}">
                            <button type="button" class="btn btn-primary button mybt" data-title="Удалить опрос">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                        </a>
                        <a href="{% url 'polls:edit' poll_id=poll.id %}">
                            <button type="button" class="btn btn-primary button mybt" data-title="Редактировать опрос">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </button>
                        </a>
                        <a href="{% url 'polls:send' poll_id=poll.id %}">
                            <button type="button" class="btn btn-primary button mybt" data-title="Отправить опрос
                            пользователю">
                                <span class="glyphicon glyphicon-bullhorn"></span>
                            </button>
                        </a>
                        {{ poll.question }}
                    </p>
                {% endfor %}
            {% else %}
                <p>No polls are available.</p>
            {% endif %}
            <p style="opacity: 1">
                <a href="{% url "polls:add_poll" %}">
                    <button type="button" class="btn btn-primary button" data-title="Добавить опрос" style="margin: 20px auto 40px auto;
    display: block;">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>

                </a>
            </p>
        </div>
        <div class="user_recieve_polls">
            <h3 class="my_h3">Полученные опросы</h3>
        <p  style="opacity: 1">
            {% for recv_poll in recv_polls %}
                <a href="{% url "polls:detail" recv_id=recv_poll.id %}">{{ recv_poll }}</a>
                <br/>
            {% empty %}
                еще нет!
            {% endfor %}
        </p>
        </div>
        <div style="clear: both"></div>
    </div>
{% endblock %}
{% block footer %}
{% endblock %}

_project_/templates/polls/results.html
{% extends "base_user.html" %}
{% block content %}
    <div class="content_box" style="width: 50%">
        <h3 style="color: #ee4c8d;">{{ poll.question }}</h3>

        {% for choice in poll.choice_set.all %}
            <p>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</p>
        {% endfor %}
    </div>
    <p style="text-align: right;">
        <a href="{% url "polls:votes_details" poll_id=poll.id %}">Подробнее о голосах</a>
    </p>
{% endblock %}

_project_/templates/polls/send.html
{% extends "base_user.html" %}
    {% block content %}
        <div class="content_box" style="width: 50%;">
            <h3 style="color: #ee4c8d;">Вопрос: {{ poll.question }}</h3>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <p>Варианты ответов:</p>
            {% for choice in poll.choice_set.all %}
                <p>{{ choice.choice_text }}</p>
            {% endfor %}
        </div>

        <form action="." method="post">
        {% csrf_token %}
        <p>{{ form.poll }}</p>
        <p>Кому: {{ form.user }}</p>
        <input type="submit" value="Отправить" class="btn btn-primary button bt"/>
        </form>
    {% endblock %}

_project_/templates/polls/votes_details.html
{% extends "base_user.html" %}
{% block content %}
    <div class="content_box" style="width: 40%; padding-top: 20px">
        {% for choice in choices %}
            <p>
                {{ choice.choice_text }}
                (Ответили:
                {% for sel_poll in  selected_poll %}
                    {% if choice.choice_text == sel_poll.answer %}
                        {{ sel_poll.user }}
                    {% else %}
                        {% if  forloop.counter == 1 %}
                            -
                        {% endif %}
                    {% endif %}
                {% endfor %}
                )</p>
        {% endfor %}
    </div>
{% endblock %}